# Generated by Django 6.0.3 on 2026-08-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('cidade', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
