# Generated by Django 6.0.3 on 2026-08-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
