# Generated by Django 6.0.3 on 2026-08-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_esporte_professor_horario_convite_participacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='especialidade',
        ),
        migrations.AddField(
            model_name='aluno',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='alunos/'),
        ),
        migrations.AddField(
            model_name='esporte',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='esportes/'),
        ),
        migrations.AddField(
            model_name='professor',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='professores/'),
        ),
    ]
