# Generated by Django 6.0.3 on 2026-10-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_professor_especialidade_aluno_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convite',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='convite',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='convite',
            name='remetente',
        ),
        migrations.AddField(
            model_name='participacao',
            name='presente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='participacao',
            constraint=models.UniqueConstraint(fields=('aluno', 'horario', 'data_participacao'), name='unico_aluno_horario_data'),
        ),
        migrations.DeleteModel(
            name='Convite',
        ),
    ]
