# Generated by Django 6.0.3 on 2026-10-04 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_convite_destinatario_remove_convite_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_antigas', to='core.aluno'),
        ),
        migrations.AlterField(
            model_name='participacao',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_antigas', to='core.horario'),
        ),
        migrations.CreateModel(
            name='MatriculaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('data_matricula', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_horarios', to='core.aluno')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_alunos', to='core.horario')),
            ],
        ),
        migrations.AddField(
            model_name='participacao',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='core.matriculahorario'),
        ),
        migrations.AddConstraint(
            model_name='matriculahorario',
            constraint=models.UniqueConstraint(fields=('aluno', 'horario'), name='unico_aluno_horario'),
        ),
    ]
