# Generated by Django 6.0.3 on 2026-10-04 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_participacao_aluno_alter_participacao_horario_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participacao',
            name='unico_aluno_horario_data',
        ),
        migrations.AlterField(
            model_name='participacao',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='core.matriculahorario'),
        ),
        migrations.AddConstraint(
            model_name='participacao',
            constraint=models.UniqueConstraint(fields=('matricula', 'data_participacao'), name='unico_matricula_data'),
        ),
        migrations.RemoveField(
            model_name='participacao',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='participacao',
            name='horario',
        ),
    ]
